// Pinia setup for Quasar. Quasar picks this file up automatically (src/stores/index)
// and installs the returned Pinia instance into the app.
// Based on the template generated by `quasar new store`:
// https://quasar.dev/quasar-cli-vite/state-management-with-pinia
import { defineStore } from '#q-app';
import { createPinia } from 'pinia';

/*
 * When adding new properties to stores, you should also
 * extend the `PiniaCustomProperties` interface.
 * @see https://pinia.vuejs.org/core-concepts/plugins.html#Typing-new-store-properties
 */
declare module 'pinia' {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  export interface PiniaCustomProperties {
    // add your custom properties here, if any
  }
}

// Quasar calls this factory once at startup (the wrapper exists so SSR could create
// a fresh store per request; for our SPA it is just a plain factory).
export default defineStore((/* { ssrContext } */) => {
  const pinia = createPinia();

  // You can add Pinia plugins here
  // pinia.use(SomePiniaPlugin)

  return pinia;
});
